name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: platformio run

      - run: echo "build_date={$(date +'%Y%m%d%H%M%S')}" >> $GITHUB_OUTPUT
        id: get_date

      - uses: actions/upload-artifact@v3
        with:
            name: frimware-${{ steps.get_date.outputs.build_date }}
            path: |
                .pio/build/nodemcu-32s/firmware.bin